Added the entry to select multiple models and verified the dockerfile
AICoE/prometheus-anomaly-detector pull request #149
Opened 2021-06-10 12:13 UTC by zanghao2

for issue #148 https://github.com/AICoE/prometheus-anomaly-detector/issues/148

2021-06-10 12:14 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fprometheus-anomaly-detector).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/prometheus-anomaly-detector/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-06-10 12:23 UTC, zanghao2 commented
/approve

2021-06-10 12:23 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/prometheus-anomaly-detector/pull/149#issuecomment-858575124" title="Approved">zanghao2</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fprometheus-anomaly-detector).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/prometheus-anomaly-detector/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-06-22 17:31 UTC, 4n4nd commented on environment.yml
> +  - python=3.6
@zanghao2 any reason the python version is being changed to `3.6`?

2021-06-22 17:37 UTC, 4n4nd requested changes
Thanks for the PR!. I have wanted to add this feature for a really long time.

I have asked a question about the dependencies ^.

Could you also update the README and add the `FLT_MODEL_TYPE` flag in it?

2021-06-22 17:37 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fprometheus-anomaly-detector).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/prometheus-anomaly-detector/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-07-15 19:37 UTC, sasah commented
https://github.com/tensorflow/models/issues/9706#issuecomment-868542761

2021-10-16 15:01 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2021-11-15 15:12 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2021-12-15 15:18 UTC, sesheta commented
Rotten issues close after 30d of inactivity.
Reopen the issue with `/reopen`.
Mark the issue as fresh with `/remove-lifecycle rotten`.

/close

2021-12-15 15:18 UTC, closed without merging

2021-12-15 15:18 UTC, sesheta commented
@sesheta: Closed this PR.

<details>

In response to [this](https://github.com/AICoE/prometheus-anomaly-detector/pull/149#issuecomment-994892554):

>Rotten issues close after 30d of inactivity.
>Reopen the issue with `/reopen`.
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>